version: '3'
services:
  app1:
    build: ./app1
    ports:
    - "5001:5000"
  app2:
    build: ./app2
    ports:
    - "5002:5000"
  nginx:
    build: ./nginx 
    ports:
    - "8080:80"
    depends_on:
      - app1
      - app2
  db:
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: westwing
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
